### ISSUE TITLE
CesiumIonSaaS.uasset not exists on server

### ISSUE THREAD

**Issue by kvuong2711** [lolleko/mesh-data-synthesizer#2]
Hi Lorenz,

When cloning the repo, I got the error:

`Error downloading object: MeshSynth/Content/CesiumSettings/CesiumIonServers/CesiumIonSaaS.uasset (21df33e): Smudge error: Error downloading MeshSynth/Content/CesiumSettings/CesiumIonServers/CesiumIonSaaS.uasset (21df33e854d9783648fc05b55800e07efb10702d5c3f8e6acc6c04a3970cc5cc): [21df33e854d9783648fc05b55800e07efb10702d5c3f8e6acc6c04a3970cc5cc] Object does not exist on the server: [404] Object does not exist on the server`

Same with other files in the repo with lfs.

Thank you!

**Comment by lolleko** [comment]
Uploaded the files, could you check if it's working?

**Comment by kvuong2711** [comment]
Yep, I could see the files now. Thanks!
